/*****************************************************************************
* Model: model.qm
* File:  port_filter/filter.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${port_filter::filter.h} .................................................*/
#ifndef _FILTER_H
#define _FILTER_H

extern QActive * const AO_filter;

/*${port_filter::filter_ctor} ..............................................*/
void filter_ctor(void);


#endif
